version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432

  app: &app
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        NODE_VERSION: '12.18.3'
    image: trick-track:0.0.1

  backend:
    <<: *app
    command: python manage.py runserver 0.0.0.0:8000 --settings=tricktrack.settings.local
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    <<: *app
    command: npm run watch
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  postgres:
  node_modules:
